# Generated by Django 3.2.8 on 2021-11-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('vendor', models.TextField()),
            ],
        ),
    ]
