print('Welcome to my Python program!', end='\n\n')
print('What is your name? ', end='')
name = input()
print('What is your favorite number? ',end='')
number = int(input())
print('What year is it? ',end='')
current_year = int(input())
print('What is your favorite restaurant? ',end='')
fav_restaurant = input()
print()
print('Your name is ' + name)
print('Your favorite number is',number)
print('Ten more than your favorite number is',number+10)
print('The year is',current_year, 'This is a cool year')
print('You like to eat at', fav_restaurant)
