# Generated by Django 3.2 on 2021-04-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_type_restaurant_typee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='typee',
            new_name='type',
        ),
    ]
